import fs from "node:fs";
import path from "node:path";

const dashboardTemplateRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), "../../templates/dashboard");
const dashboardMarker = ".harness-dashboard";

export function writeJsonFile(filePath, value) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

export function copyDashboardAssets(outDir) {
  copyDirectory(dashboardTemplateRoot, outDir);
}

export function writeDashboardDirectory(outDir, bundle, options = {}) {
  const target = path.resolve(outDir);
  assertSafeDashboardTarget(target, options);
  if (fs.existsSync(target)) fs.rmSync(target, { recursive: true, force: true });
  copyDashboardAssets(target);
  fs.writeFileSync(path.join(target, dashboardMarker), "generated dashboard directory\n");
  writeJsonFile(path.join(target, "data/status.json"), bundle.status);
  writeJsonFile(path.join(target, "data/tables.json"), bundle.tables);
  writeJsonFile(path.join(target, "data/documents.json"), bundle.documents);
  writeJsonFile(path.join(target, "data/graph.json"), bundle.graph);
  writeJsonFile(path.join(target, "data/adoption.json"), bundle.adoption);
  fs.writeFileSync(
    path.join(target, "assets/dashboard-data.js"),
    `window.__HARNESS_DASHBOARD__ = ${JSON.stringify(bundle, null, 2)};\n`,
  );
  fs.writeFileSync(
    path.join(target, "README.md"),
    [
      "# Harness Dashboard",
      "",
      "This is a read-only static snapshot generated by `harness dashboard --out-dir`.",
      "Open `index.html` directly in a browser. No target project files are read at browser runtime.",
      "",
    ].join("\n"),
  );
  return target;
}

function assertSafeDashboardTarget(target, options) {
  const protectedRoots = [
    path.parse(target).root,
    process.env.HOME,
    options.repoRoot,
    options.projectRoot,
    options.docsRoot,
    dashboardTemplateRoot,
  ].filter(Boolean).map((item) => path.resolve(item));
  if (protectedRoots.includes(target)) {
    throw new Error(`Refusing unsafe dashboard output directory: ${target}`);
  }
  for (const root of [options.docsRoot, dashboardTemplateRoot].filter(Boolean).map((item) => path.resolve(item))) {
    if (isPathInside(target, root)) {
      throw new Error(`Refusing dashboard output inside protected directory: ${target}`);
    }
  }
  if (fs.existsSync(target)) {
    const entries = fs.readdirSync(target);
    const hasMarker = fs.existsSync(path.join(target, dashboardMarker));
    if (entries.length > 0 && !hasMarker) {
      throw new Error(`Refusing to overwrite non-dashboard directory: ${target}`);
    }
  }
}

function isPathInside(candidate, parent) {
  const relative = path.relative(parent, candidate);
  return Boolean(relative) && !relative.startsWith("..") && !path.isAbsolute(relative);
}

function copyDirectory(from, to) {
  if (!fs.existsSync(from)) throw new Error(`Missing dashboard template directory: ${from}`);
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const source = path.join(from, entry.name);
    const destination = path.join(to, entry.name);
    if (entry.isDirectory()) {
      copyDirectory(source, destination);
    } else {
      fs.copyFileSync(source, destination);
    }
  }
}
